### ISSUE TITLE
Example with gifs?

### ISSUE THREAD

**Issue by hisRoyalty** [jhuckaby/canvas-plus#17]
@jhuckaby i'm not sure how i'd work with the gifs
I've used the example, for the gif. However, it returns only the first frame of the gif (non-animated)
Is it *supposed* to be like this?

**Comment by jhuckaby** [comment]
Hey there!  Yeah, this is actually by design with the HTML5 Canvas.  If you draw a GIF image onto a canvas, you only get the first frame.  canvas-plus is just a wrapper around the native HTML5 canvas, so it has the same limitation.

You may be able to slice up your GIF into separate frame images using a 3rd party library such as https://www.npmjs.com/package/gif-frames

**Comment by hisRoyalty** [comment]
Oh thanks!
